# ==============================================================================
# Title: Thesis Dashboard Generator
# Purpose: Compile all thesis figures into an interactive HTML dashboard.
# Author: Luan Blakaj 齐凯
# ==============================================================================

if (!require("pacman")) install.packages("pacman")
pacman::p_load(rmarkdown, knitr, tidyverse)

# 1. METADATE & FIGURELISTE DEFINIERE ------------------------------------------
# Mir kategorisiere jedi Figure mit Tags zum Filtere.

all_figures <- list()

add_fig <- function(id, path, title, explanation, formula = NULL, tags = c()) {
    list(
        id = id,
        path = path,
        title = title,
        explanation = explanation,
        formula = formula,
        tags = tags
    )
}

# --- GRUPPE 0: KERN-SCM (Skript 04, 05) ---
all_figures[[length(all_figures) + 1]] <- add_fig(
    "SCM-01", "outputs/scm_optimized_fit.png", "Hybrid SCM Fit",
    "The primary result. Comparison of Real monthly data vs Annual Synthetic counterfactual.",
    "$$ Gap_t = Y_{France,t} - \\sum w_j^* Y_{Donor,t} $$",
    c("SCM", "Core")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "SCM-02", "outputs/MASTER_SCM_PLOT.png", "Master Pipeline Plot",
    "Generated by the full pipeline script (05), confirming the optimized SCM fit.",
    "$$ Gap_t = Y_{France,t} - Y_{Synthetic,t} $$",
    c("SCM", "Core")
)

# --- GRUPPE 1: KERN-FIGURE (Skript 06) ---
path_06 <- "outputs/figures_final"
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Trend-01", file.path(path_06, "Fig1_Overall_Trend_Laws.png"), "Overall Trend & Laws",
    "Monthly incidents with vertical lines for key legislative changes.",
    "$$ Y_t = \\sum Incidents_t $$",
    c("Trend", "Laws")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Placebo-01", file.path(path_06, "Fig2_Placebo_Test.png"), "Placebo: Burglary",
    "Comparing Assaults on State Authority vs Burglary to rule out general crime waves.",
    "$$ Ratio_t = \\frac{Index_{Violence,t}}{Index_{Crime,t}} $$",
    c("Robustness", "Placebo")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Spatial-01", file.path(path_06, "Fig3_Paris_vs_Rest.png"), "Paris vs Rest",
    "Absolute counts showing divergence between Capital and Provinces.",
    "$$ Y_{Paris,t} \\text{ vs } Y_{Rest,t} $$",
    c("Spatial")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Season-01", file.path(path_06, "Fig4_Seasonality_Heatmap.png"), "Seasonality Heatmap",
    "Visualizing intensity by month/year.",
    "$$ Cell_{m,y} = Count_{m,y} $$",
    c("Trend", "Seasonality")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "SCM-03", file.path(path_06, "Fig5_SCM_Gap.png"), "SCM Gap (Annual)",
    "Annual difference bar chart.",
    "$$ \\Delta_y = Y_{Fra,y} - Y_{Syn,y} $$",
    c("SCM")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Cat-01", file.path(path_06, "Fig6_Category_Breakdown.png"), "Category Breakdown",
    "Facetted view of sub-types.",
    "$$ Y_{c,t} = \\sum Incidents_{c,t} $$",
    c("Trend", "Categories")
)

# --- GRUPPE 2: ERWITERETI FIGURE (Skript 07) ---
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Trend-02", file.path(path_06, "FigA1_Overall_Trend.png"), "Overall Trend (Alt)",
    "Alternative rendering of the main timeline.",
    "$$ Y_t $$",
    c("Trend")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Zoom-2015", file.path(path_06, "FigB1_Zoom_Emergency2015.png"), "Zoom: 2015 Emergency",
    "24-month window around Nov 2015.",
    "$$ Y_t |_{t \\in [t^*-24, t^*+24]} $$",
    c("Laws", "2015")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Zoom-2017", file.path(path_06, "FigB2_Zoom_SILT2017.png"), "Zoom: 2017 SILT",
    "24-month window around Oct 2017.",
    "$$ Y_t |_{t \\in [t^*-24, t^*+24]} $$",
    c("Laws", "2017")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Zoom-2021", file.path(path_06, "FigB3_Zoom_Separatism2021.png"), "Zoom: 2021 Separatism",
    "24-month window around Aug 2021.",
    "$$ Y_t |_{t \\in [t^*-24, t^*+24]} $$",
    c("Laws", "2021")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Spatial-02", file.path(path_06, "FigC1_Spatial_Absolute.png"), "Spatial Counts",
    "Paris v Suburbs v Rest.",
    "$$ Y_{region,t} $$",
    c("Spatial")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Spatial-03", file.path(path_06, "FigC2_Spatial_Indexed.png"), "Spatial Indexed",
    "Growth rates (2010=100) comparison.",
    "$$ I_{r,t} = \\frac{Y_{r,t}}{Y_{r,2010}} \\times 100 $$",
    c("Spatial")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Spatial-04", file.path(path_06, "FigC3_Spatial_Share.png"), "Donut Effect",
    "Share of Suburbs vs Paris.",
    "$$ R = \\frac{S}{S+P} $$",
    c("Spatial")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Placebo-02", file.path(path_06, "FigD1_Placebo_Test.png"), "Placebo (Alt)",
    "Robustness check variation.",
    "$$ Ratio = \\frac{Index_{Political}}{Index_{Conventional}} $$",
    c("Robustness")
)

# --- GRUPPE 3: FORTGESCHRITTNI ANALYSE (Skript 08) ---
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Stat-01", file.path(path_06, "Fig_New_A1_RollingVolatility.png"), "Rolling Volatility",
    "Standard deviation over 12 months.",
    "$$ \\sigma_t = \\sqrt{\\frac{1}{12} \\sum_{i=0}^{11} (x_{t-i} - \\bar{x})^2} $$",
    c("Stats")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Stat-02", file.path(path_06, "Fig_New_A2_STL_Decomposition.png"), "STL Decomposition",
    "Seasonal-Trend separation.",
    "$$ Y_t = S_t + T_t + R_t $$",
    c("Stats")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Stat-03", file.path(path_06, "Fig_New_A3_LagPlot.png"), "Lag Plot",
    "Autocorrelation check (t vs t-1).",
    "$$ \\rho_1 = Corr(Y_t, Y_{t-1}) $$",
    c("Stats")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Stat-04", file.path(path_06, "Fig_New_A4_LongTermHistory.png"), "Long Term History",
    "Stitched DataGouv + SSMSI (1996-2022).",
    "$$ Y_t = Y_{Historical} \\cup Y_{Modern} $$",
    c("Trend", "LongData")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Stat-05", file.path(path_06, "Fig_New_A5_StructuralBreaks.png"), "Struct Break (Chow)",
    "F-statistics for regime change detection.",
    "$$ F = \\frac{RSS_R - RSS_U}{RSS_U / (n-2k)} $$",
    c("Stats", "Tests")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Map-01", file.path(path_06, "Fig_New_B1_GTD_Map.png"), "GTD Terror Map",
    "Point map of terror incidents.",
    "$$ Coord_i = (lat_i, lon_i) $$",
    c("Maps", "Terror")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Map-02", file.path(path_06, "Fig_New_B2_ACLED_Heatmap.png"), "ACLED Heatmap",
    "Density of modern violence.",
    "$$ Density(x,y) = \\frac{1}{n} \\sum K_H(x - X_i) $$",
    c("Maps")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Map-03", file.path(path_06, "Fig_New_B4_Dept_Growth.png"), "Dept Growth",
    "Map of % Change by Department.",
    "$$ \\Delta\\%_d = \\frac{Y_{d,2022} - Y_{d,2015}}{Y_{d,2015}} $$",
    c("Maps")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Spatial-Disp-01", file.path(path_06, "Fig6_Dispersion_HHI.png"), "Dispersion: HHI",
    "Departmental concentration (quarterly-smoothed HHI), descriptive only.",
    "$$ HHI_t = \\sum_i s_{it}^2, \\quad s_{it}=\\frac{y_{it}}{\\sum_i y_{it}} $$",
    c("Spatial", "Stats", "Corroborative")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Spatial-Disp-02", file.path(path_06, "Fig6_Dispersion_SD.png"), "Dispersion: Spatial SD",
    "Weighted geographic spread radius using department centroids (km), descriptive only.",
    "$$ SD_t = \\sqrt{\\sum_i s_{it}\\left[(x_i-\\bar{x}_t)^2 + (y_i-\\bar{y}_t)^2\\right]} $$",
    c("Spatial", "Stats", "Corroborative")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Spatial-TS-01", file.path(path_06, "Fig6_TargetShift_TSR.png"), "Target Shift (TSR)",
    "Proxy target-shift ratio over time (hard vs soft), descriptive/corroborative.",
    "$$ TSR_t = \\frac{Hard_t}{Hard_t + Soft_t} $$",
    c("Spatial", "Corroborative", "Substitution")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Spatial-TS-02", file.path(path_06, "Fig6_TargetShift_TSR_Regions.png"), "Target Shift by Region",
    "Core-periphery balance (Paris, Petite Couronne, Rest) for target-shift proxy.",
    "$$ TSR_{r,t} = \\frac{Hard_{r,t}}{Hard_{r,t} + Soft_{r,t}} $$",
    c("Spatial", "Corroborative", "Substitution")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Spatial-Donut-02", file.path(path_06, "Fig6_DonutRatio_Updated.png"), "Donut Ratio (Updated)",
    "Ring/Center ratio with SILT and PTR markers plus pre/post means.",
    "$$ Ratio_t = \\frac{Ring_t}{Center_t} $$",
    c("Spatial", "Corroborative", "CorePeriphery")
)

# --- GRUPPE 4: ERGÄNZENDI FIGURE (Skript 09) ---
path_09 <- "outputs/figures_additional"
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Trend-Add-01", file.path(path_09, "FigE1_Category_Trends.png"), "Category Trends",
    "Supplementary category breakdown.",
    "$$ Y_{c,t} $$",
    c("Trend")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Trend-Add-02", file.path(path_09, "FigE2_Political_Rolling12.png"), "Rolling Mean",
    "Smoothed trends.",
    "$$ \\bar{Y}_t = \\frac{1}{12} \\sum_{i=0}^{11} Y_{t-i} $$",
    c("Trend")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Stat-Add-01", file.path(path_09, "FigE4_Pre_Post_Change.png"), "Pre/Post Change",
    "Bar chart of % change.",
    "$$ \\Delta\\% = \\frac{\\mu_{post} - \\mu_{pre}}{\\mu_{pre}} \\times 100 $$",
    c("Stats")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Trend-Add-03", file.path(path_09, "FigE6_Cumulative.png"), "Cumulative Count",
    "Integral of violence over time.",
    "$$ C_t = \\sum_{i=1}^t Y_i $$",
    c("Trend")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Map-Add-01", file.path(path_09, "FigF1_Top_Departments.png"), "Top Departments",
    "Bar chart of most violent depts.",
    "$$ Y_d = \\sum_t Y_{d,t} $$",
    c("Spatial")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Map-Add-02", file.path(path_09, "FigF3_Department_Slope_Change.png"), "Slope Change",
    "Acceleration by department.",
    "$$ \\Delta \\beta_d = \\beta_{d,post} - \\beta_{d,pre} $$",
    c("Spatial")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Event-01", file.path(path_09, "FigG1_Event_Study_2015.png"), "Event Study 2015",
    "Mean incidents +/- 24m.",
    "$$ E_k = \\bar{Y}_{t^*+k} $$",
    c("Laws", "2015")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Event-02", file.path(path_09, "FigG2_Event_Study_2017.png"), "Mean incidents +/- 24m.",
    "$$ E_k = \\bar{Y}_{t^*+k} $$",
    c("Laws", "2017")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Event-03", file.path(path_09, "FigG3_Event_Study_2021.png"), "Event Study 2021",
    "Mean incidents +/- 24m.",
    "$$ E_k = \\bar{Y}_{t^*+k} $$",
    c("Laws", "2021")
)

# --- GRUPPE 5: HYPOTHESE & STABILITÄT (Skript 11, 13, 15) ---
path_11 <- "outputs/tests"
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Test-01", file.path(path_11, "Hypothesis_Test_FR2015_ESTATE.png"), "Hypothesis 2015",
    "Formal structural break check.",
    "$$ H_0: \\beta_{pre} = \\beta_{post} $$",
    c("Tests", "2015")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Test-02", file.path(path_11, "Hypothesis_Test_FR2017_SILT.png"), "Hypothesis 2017",
    "Formal structural break check.",
    "$$ H_0: \\beta_{pre} = \\beta_{post} $$",
    c("Tests", "2017")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Test-03", file.path(path_11, "Impact_vs_Synth_Gap.png"), "Gap Analysis (Full)",
    "Significant deviations from synthetic.",
    "$$ G_t = Y_t - Y^*_{t} $$",
    c("SCM", "Tests")
)

path_13 <- "outputs/robustness"
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Var-01", file.path(path_13, "T_V2.png"), "Log-Transformed Gap",
    "Gap analysis using log scale.",
    "$$ \\ln(Y_t) - \\ln(Y^*_t) $$",
    c("SCM", "Robustness")
)

path_15 <- "outputs/robustness/final"
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Stability-Heat", file.path(path_15, "Significance_Heatmap.png"), "Stability Heatmap",
    "Summary of Equivalence Tests.",
    "$$ p_{TOST} < 0.05 $$",
    c("Tests", "Core")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Stability-2015", file.path(path_15, "Stability_Proof_FR2015_ESTATE.png"), "Proof: 2015",
    "TOST proof of stability for 2015.",
    "$$ -\\Delta < \\beta_{diff} < \\Delta $$",
    c("Tests", "2015")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Stability-2017", file.path(path_15, "Stability_Proof_FR2017_SILT.png"), "Proof: 2017",
    "TOST result for 2017.",
    "$$ -\\Delta < \\beta_{diff} < \\Delta $$",
    c("Tests", "2017")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Stability-2021", file.path(path_15, "Stability_Proof_FR2021_PACTI.png"), "Proof: 2021",
    "TOST proof of stability for 2021.",
    "$$ -\\Delta < \\beta_{diff} < \\Delta $$",
    c("Tests", "2021")
)

# --- GRUPPE 6: ANIMATIONE (Skript 10 - Statischi Vorschou) ---
path_10 <- "outputs/animation"
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Anim-SSMSI", file.path(path_10, "serieschrono_center_trajectory.png"), "Center Gravity (SSMSI)",
    "Trajectory of the weighted mean center of violence (1996-2022).",
    "$$ (\\bar{X}_t, \\bar{Y}_t) = \\sum w_i (x_i, y_i) / \\sum w_i $$",
    c("Spatial", "Animations")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Anim-ACLED", file.path(path_10, "acled_center_trajectory.png"), "Center Gravity (ACLED)",
    "Trajectory for 2020-2025 events.",
    "$$ (\\bar{X}_t, \\bar{Y}_t) $$",
    c("Spatial", "Animations")
)
all_figures[[length(all_figures) + 1]] <- add_fig(
    "Anim-GTD", file.path(path_10, "gtd_center_trajectory.png"), "Center Gravity (GTD)",
    "Trajectory for Terrorism (2010-2021).",
    "$$ (\\bar{X}_t, \\bar{Y}_t) $$",
    c("Spatial", "Animations")
)

# 2. HTML GENERIERE ------------------------------------------------------------
html_file <- file.path("outputs", "Thesis_Dashboard.html")
sink(html_file)

cat("<!DOCTYPE html>\n<html lang='en'>\n<head>\n")
cat("<meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'>\n")
cat("<title>Thesis Dashboard: Violence in France</title>\n")
# MathJax ybunde
cat("<script src=\"https://polyfill.io/v3/polyfill.min.js?features=es6\"></script>\n")
cat("<script id=\"MathJax-script\" async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"></script>\n")

# CSS Styling
cat("body { font-family: 'Times New Roman', serif; margin: 0; padding: 0; display: flex; height: 100vh; background: #f4f4f4; }\n")
cat("/* Sidebar */\n")
cat(".sidebar { width: 250px; background: #1a1a1a; color: #fff; overflow-y: auto; padding: 20px; box-sizing: border-box; flex-shrink: 0; }\n")
cat(".sidebar h2 { color: #8A0000; font-size: 1.2em; border-bottom: 1px solid #444; padding-bottom: 10px; }\n")
cat(".sidebar a { display: block; color: #ccc; text-decoration: none; padding: 8px 0; font-size: 0.9em; transition: 0.2s; }\n")
cat(".sidebar a:hover { color: #fff; padding-left: 5px; }\n")
cat("/* Main Content */\n")
cat(".main { flex-grow: 1; overflow-y: auto; padding: 20px 40px; box-sizing: border-box; }\n")
cat("h1 { color: #8A0000; border-bottom: 2px solid #8A0000; padding-bottom: 10px; }\n")
cat("/* Filter Bar */\n")
cat(".filter-bar { background: #fff; padding: 15px; margin-bottom: 20px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); display: flex; gap: 15px; align-items: center; position: sticky; top: 0; z-index: 100; }\n")
cat(".filter-btn { padding: 8px 15px; border: 1px solid #ccc; background: #f9f9f9; cursor: pointer; border-radius: 4px; font-family: sans-serif; font-size: 0.9em; }\n")
cat(".filter-btn:hover, .filter-btn.active { background: #8A0000; color: white; border-color: #8A0000; }\n")
cat("/* Figure Cards */\n")
cat(".fig-card { background: #fff; padding: 20px; margin-bottom: 30px; border-radius: 5px; box-shadow: 0 2px 8px rgba(0,0,0,0.05); transition: 0.3s; }\n")
cat(".fig-card:hover { box-shadow: 0 5px 15px rgba(0,0,0,0.1); }\n")
cat(".fig-card h3 { margin-top: 0; color: #444; display: flex; justify-content: space-between; align-items: center; }\n")
cat(".fig-id { font-size: 0.8em; background: #eee; padding: 2px 6px; border-radius: 3px; color: #666; }\n")
cat("/* New: Image constrained to max size */\n")
cat("img { max-width: 100%; max-height: 400px; width: auto; height: auto; border: 1px solid #eee; display: block; margin: 15px auto; box-shadow: 0 1px 3px rgba(0,0,0,0.1); cursor: zoom-in; }\n")
cat("img:active { max-height: none; cursor: zoom-out; } /* Simple click-to-zoom */\n")
cat(".explanation { background: #f9f9f9; padding: 10px; border-left: 4px solid #8A0000; color: #555; font-style: italic; }\n")
cat(".formula { background: #fff; padding: 10px; border: 1px dashed #ccc; margin-top: 10px; font-family: 'Times New Roman'; text-align: center; position: relative; }\n")
cat(".copy-btn { position: absolute; right: 5px; top: 5px; background: #eee; border: 1px solid #ccc; font-size: 0.7em; cursor: pointer; padding: 2px 5px; border-radius: 3px; }\n")
cat(".copy-btn:hover { background: #ddd; }\n")
cat(".tags { margin-top: 10px; }\n")
cat(".tag { display: inline-block; background: #e0e0e0; padding: 2px 8px; border-radius: 10px; font-size: 0.75em; color: #555; margin-right: 5px; }\n")
cat("</style>\n</head>\n<body>\n")


# SIDEBAR Navigation
cat("<h2>Navigation</h2>\n")
for (fig in all_figures) {
    cat(paste0("<a href='#", fig$id, "'>", fig$id, ": ", fig$title, "</a>\n"))
}
cat("</div>\n")

# HAUPTBEREICH
cat("<h1>Thesis Visualizations Dashboard</h1>\n")

# Filter-Zyleischte
cat("<strong>Filters:</strong>")
cat("<button class='filter-btn active' onclick=\"filterSelection('all')\">Show All</button>\n")
cat("<button class='filter-btn' onclick=\"filterSelection('SCM')\">SCM Models</button>\n")
cat("<button class='filter-btn' onclick=\"filterSelection('Spatial')\">Spatial</button>\n")
cat("<button class='filter-btn' onclick=\"filterSelection('Tests')\">Stat Tests</button>\n")
cat("<button class='filter-btn' onclick=\"filterSelection('2015')\">2015 Law</button>\n")
cat("<button class='filter-btn' onclick=\"filterSelection('2017')\">2017 Law</button>\n")
cat("</div>\n")

# Figure duregange
    classes <- paste(c("fig-card", fig$tags), collapse = " ")

    cat(paste0("<div class='", classes, "' id='", fig$id, "'>\n"))
    cat(paste0("<h3>", fig$title, " <span class='fig-id'>", fig$id, "</span></h3>\n"))

    if (file.exists(fig$path)) {
        rel_path <- sub("^outputs/", "", fig$path) # Aapassig fir relativ Pfad ab HTML-Standort
        # Eigetlig isch HTML in outputs/, also bruuche mr nur Dateiname wenn glych Verzeichnis, oder Subverzeichnis
        # HTML in outputs/, Figur in outputs/figures_final/ -> figures_final/Fig...

        # Robusti Pfad-Behandlig
        if (grepl("outputs/", fig$path)) {
            rel_path <- sub("outputs/", "", fig$path)
        } else {
            rel_path <- fig$path
        }

        cat(paste0("<img src='", rel_path, "' alt='", fig$title, "'>\n"))
    } else {
        cat(paste0("<p style='color:red;'>Image missing: ", fig$path, "</p>\n"))
    }

    cat(paste0("<div class='explanation'>", fig$explanation, "</div>\n"))

    if (!is.null(fig$formula)) {
        # Backslashes fir JS-String maskiere (eifachi Methode) oder roh Text fir Aazeig
        # Mir bruuche e data-formula Attribut fir dr Copy-Chnopf
        # HINWYS: In R String-Literale wird Doppel-Backslash fir LaTeX bruucht.
        cat(paste0(
            "<div class='formula'>", fig$formula,
            "<button class='copy-btn' onclick='copyFormula(this)'>Copy LaTeX</button>",
            "<span style='display:none' class='tex-source'>", fig$formula, "</span></div>\n"
        ))
    }

    # Tags darschtelle
    cat("<div class='tags'>")
    for (t in fig$tags) {
        cat(paste0("<span class='tag'>", t, "</span>"))
    }
    cat("</div>\n")

    cat("</div>\n")
}

cat("</div>\n") # End Hauptbereich

# Javascript fir Filterig
cat("<script>\n")
cat("function filterSelection(c) {\n")
cat("  var x, i;\n")
cat("  x = document.getElementsByClassName('fig-card');\n")
cat("  if (c == 'all') c = '';\n")
cat("  for (i = 0; i < x.length; i++) {\n")
cat("    w3RemoveClass(x[i], 'show');\n")
cat("    if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], 'show');\n")
cat("  }\n")
cat("  // Update buttons\n")
cat("  var btns = document.getElementsByClassName('filter-btn');\n")
cat("  for (var i = 0; i < btns.length; i++) {\n")
cat("    btns[i].classList.remove('active');\n")
cat("    if(btns[i].innerText.indexOf(c) > -1 || (c=='' && btns[i].innerText=='Show All')) btns[i].classList.add('active'); \n")
cat("  }\n")
cat("}\n")

cat("function w3AddClass(element, name) {\n")
cat("  var i, arr1, arr2;\n")
cat("  arr1 = element.className.split(' ');\n")
cat("  arr2 = name.split(' ');\n")
cat("  for (i = 0; i < arr2.length; i++) {\n")
cat("    if (arr1.indexOf(arr2[i]) == -1) {element.className += ' ' + arr2[i];}\n")
cat("  }\n")
cat("}\n")

cat("function w3RemoveClass(element, name) {\n")
cat("  var i, arr1, arr2;\n")
cat("  arr1 = element.className.split(' ');\n")
cat("  arr2 = name.split(' ');\n")
cat("  for (i = 0; i < arr2.length; i++) {\n")
cat("    while (arr1.indexOf(arr2[i]) > -1) {\n")
cat("      arr1.splice(arr1.indexOf(arr2[i]), 1);\n")
cat("    }\n")
cat("  }\n")
cat("  element.className = arr1.join(' ');\n")
cat("}\n")

cat("// Init: Show all\n")
cat("filterSelection('all');\n")

cat("function copyFormula(btn) {\n")
cat("  var tex = btn.nextSibling.innerText;\n")
cat("  // Remove dollar signs for raw latex if desirable? Let's keep them as requested usually or remove\n")
cat("  // User asked for formula to keyboard. Typically without $$ for inline or with.\n")
cat("  // Let's strip $$ for cleaner copy.\n")
cat("  tex = tex.replace(/^\\$\\$\\s*/, '').replace(/\\s*\\$\\$$/, '');\n")
cat("  navigator.clipboard.writeText(tex).then(function() {\n")
cat("    var original = btn.innerText;\n")
cat("    btn.innerText = 'Copied!';\n")
cat("    setTimeout(function(){ btn.innerText = original; }, 1500);\n")
cat("  });\n")
cat("}\n")
cat("</script>\n")

# CSS-Hilf fir aazeig/verstecke (Display yberschrybe)
cat("<style>\n")
cat(".fig-card { display: none; }\n") # Standardmässig versteckt
cat(".show { display: block; animation: fadeEffect 0.5s; }\n")
cat("@keyframes fadeEffect { from {opacity: 0;} to {opacity: 1;} }\n")
cat("</style>\n")

cat("</body>\n</html>")
sink()

print(paste("Dashboard generated at:", html_file))
